// Dados das 6 espécies detalhadas e índice das 34
window.AVES_DETALHADAS = [
  {
    slug: "seriema",
    numero: "01",
    nome: "Seriema",
    cientifico: "Cariama cristata",
    tamanho: "70 a 90 cm",
    cor: "Cinza-claro, pernas vermelhas, crista penacho",
    som: "Gargalhada longa e estridente",
    fato: "Quase não voa — prefere correr. Pode atingir 70 km/h nas pernas longas e ágeis.",
    curiosidade: 'Seu canto se ouve a 1 quilômetro de distância. Os antigos a chamavam de "relógio do cerrado" porque cantava em horários certos do dia.',
    cor_destaque: "#A0392E",
    credito: "Charles J. Sharp / Wikimedia Commons / CC BY-SA 4.0"
  },
  {
    slug: "ema",
    numero: "02",
    nome: "Ema",
    cientifico: "Rhea americana",
    tamanho: "130 a 170 cm de altura",
    cor: "Acinzentada, plumas grandes, pescoço longo",
    som: "Estrondo grave, como um trovão distante",
    fato: "É a maior ave do Brasil. Não voa, mas corre a 60 km/h em campo aberto.",
    curiosidade: "É o macho quem cuida dos ovos e dos filhotes. A mãe põe os ovos e segue caminho — o pai choca por mais de 40 dias.",
    cor_destaque: "#8B4513",
    credito: "H. Zell / Wikimedia Commons / CC BY-SA 3.0"
  },
  {
    slug: "arara-azul-grande",
    numero: "03",
    nome: "Arara-azul-grande",
    cientifico: "Anodorhynchus hyacinthinus",
    tamanho: "95 a 100 cm",
    cor: "Azul cobalto profundo, anel amarelo ao redor dos olhos",
    som: '"Krrrak, krrrak" grave',
    fato: "É a maior arara do mundo. Vive até 50 anos e escolhe um único parceiro para a vida toda.",
    curiosidade: "Sua mordida tem força de 90 quilos — quebra coquinho de macaúba sem esforço nenhum.",
    cor_destaque: "#2C5F8D",
    credito: "Charles J. Sharp / Wikimedia Commons / CC BY-SA 4.0"
  },
  {
    slug: "tucano-toco",
    numero: "04",
    nome: "Tucano-toco",
    cientifico: "Ramphastos toco",
    tamanho: "55 a 65 cm",
    cor: "Preto, peito branco-amarelado, bico laranja vibrante",
    som: '"Croque, croque, croque"',
    fato: "É o maior tucano do mundo. Seu bico pode ter 20 cm — maior que a mão aberta de uma criança.",
    curiosidade: "O bico parece pesado, mas é cheio de bolsas de ar por dentro. Leve como uma esponja.",
    cor_destaque: "#E8A317",
    credito: "Giles Laurent / Wikimedia Commons / CC BY-SA 4.0"
  },
  {
    slug: "curicaca",
    numero: "05",
    nome: "Curicaca",
    cientifico: "Theristicus caudatus",
    tamanho: "70 a 80 cm",
    cor: "Corpo cinza, asas pretas, cabeça e pescoço cor de canela",
    som: '"Curi-caca, curi-caca" — alto e ritmado',
    fato: "Voa em bandos formando um V no céu, anunciando o fim da tarde no cerrado.",
    curiosidade: 'Seu nome vem do próprio canto. Os índios Tupi a chamavam assim porque ela parece dizer o próprio nome.',
    cor_destaque: "#5D7C3F",
    credito: "Charles J. Sharp / Wikimedia Commons / CC BY-SA 4.0"
  },
  {
    slug: "pato-mergulhao",
    numero: "06",
    nome: "Pato-mergulhão",
    cientifico: "Mergus octosetaceus",
    tamanho: "49 a 56 cm",
    cor: "Cabeça verde-escura, corpo cinza, peito branco",
    som: "Sopros e roncos curtos",
    fato: "É uma das aves mais raras do mundo. Restam menos de 250 indivíduos, vivendo em rios limpos do cerrado.",
    curiosidade: "Mergulha embaixo d'água para caçar. Só vive em rios cristalinos — onde tem pato-mergulhão, a água é pura.",
    cor_destaque: "#2C5F8D",
    ameacado: true,
    credito: "Sávio Freire Bruno / Wikimedia Commons / CC BY-SA 3.0"
  }
];

// Banco completo das 34 espécies (todas têm foto em banco-aves/<slug>.jpg)
window.BANCO_AVES = [
  { slug: "anhuma-poca",            nome: "Anhuma-poca / Tachã" },
  { slug: "aracua-do-pantanal",     nome: "Aracuã-do-pantanal" },
  { slug: "aracari-castanho",       nome: "Araçari-castanho" },
  { slug: "arara-azul-grande",      nome: "Arara-azul-grande" },
  { slug: "arara-caninde",          nome: "Arara-canindé" },
  { slug: "arara-vermelha-grande",  nome: "Arara-vermelha-grande" },
  { slug: "asa-branca",             nome: "Asa-branca" },
  { slug: "cabure",                 nome: "Caburé" },
  { slug: "codorna-do-nordeste",    nome: "Codorna-do-nordeste" },
  { slug: "coruja-buraqueira",      nome: "Coruja-buraqueira" },
  { slug: "coruja-da-igreja",       nome: "Coruja-da-igreja" },
  { slug: "coruja-orelhuda",        nome: "Coruja-orelhuda" },
  { slug: "curicaca",               nome: "Curicaca" },
  { slug: "ema",                    nome: "Ema" },
  { slug: "garca-moura",            nome: "Garça-moura" },
  { slug: "inhambu-chororo",        nome: "Inhambu-chororó" },
  { slug: "inhambu-xinta",          nome: "Inhambu-xintã" },
  { slug: "jacucaca",               nome: "Jacucaca" },
  { slug: "jao",                    nome: "Jaó" },
  { slug: "juriti-pupu",            nome: "Juriti-pupu" },
  { slug: "marreca-de-coleira",     nome: "Marreca-de-coleira" },
  { slug: "mutum-de-penacho",       nome: "Mutum-de-penacho" },
  { slug: "papagaio-verdadeiro",    nome: "Papagaio-verdadeiro" },
  { slug: "pato-mergulhao",         nome: "Pato-mergulhão" },
  { slug: "pavaozinho-do-para",     nome: "Pavãozinho-do-pará" },
  { slug: "pe-vermelho",            nome: "Pé-vermelho" },
  { slug: "periquitao-maracana",    nome: "Periquitão-maracanã" },
  { slug: "pomba-de-bando",         nome: "Pomba-de-bando" },
  { slug: "pomba-galega",           nome: "Pomba-galega" },
  { slug: "pomba-trocal",           nome: "Pomba-trocal" },
  { slug: "seriema",                nome: "Seriema" },
  { slug: "tucano-de-bico-preto",   nome: "Tucano-de-bico-preto" },
  { slug: "tucano-toco",            nome: "Tucano-toco / Tucanuçu" },
  { slug: "tapaculo-de-brasilia",   nome: "Tapaculo-de-brasília" }
];
